using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using MiniJSON;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;

[Generator]
internal class JsonConstIncrementalGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        Debugger.Launch();
        // Watch for additional file called permissions.json
        var jsonFiles = context.AdditionalTextsProvider
            .Where(file => Path.GetFileName(file.Path).EndsWith("permissionsTags.json", StringComparison.OrdinalIgnoreCase));

        var combined = jsonFiles
            .Select((text, _) => text.GetText()!.ToString());

        context.RegisterSourceOutput(combined, (ctx, json) =>
        {
            var output = GenerateFromJson(json, "filename", "namespace", "jsonFileName", ".");
            if(output != null) 
                ctx.AddSource("Permissions.g.cs", SourceText.From(output, Encoding.UTF8));
        });
    }

    private string GenerateFromJson(string json, string fileName, string @namespace, string jsonFileName, string seperator)
    {
        var doc = Json.Deserialize(json);

        var sb = new StringBuilder();

        sb.AppendLine("using JsonConstGenerator;");
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine(Environment.NewLine);
        sb.AppendLine($"//Generated by {jsonFileName}");
        sb.AppendLine($"public static partial class {fileName}");
        sb.AppendLine("{");


        var paths = new List<string>();
        if(doc is Dictionary<string, object> dict)
        {
            foreach(var item in dict)
            {
                GenerateRecursive(item.Value, sb, item.Key, 1, item.Key, paths, seperator);
            }

        }
        sb.AppendLine(Environment.NewLine);
        sb.AppendLine(Environment.NewLine);
        sb.AppendLine("    public IEnumerable<JsonConstNode>> GetAll()");
        sb.AppendLine("    {");
        for(int i=0;i<paths.Count; i++)
        {
            sb.Append($"       yield return {paths[i]};");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateRecursive(object element, StringBuilder sb, string className, int indentLevel, string path, List<string> endpaths, string seperator)
    {
        string indent = new string(' ', indentLevel * 4);

        if(element is Dictionary<string, object> dict && dict.Any())
        {
            sb.AppendLine($"{indent}public static class {className} : JsonConstNode");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public static JsonConstNode self = new(\"{path}\");");
            foreach (var item in dict)
            {
                var childClass = item.Key;
                var value = item.Value;
                GenerateRecursive(item.Value, sb, childClass, indentLevel+1, $"{path}.{childClass}", endpaths, seperator);
            }
            sb.AppendLine($"{indent}}}");
        }
        else if(element is List<object> list)
        {
            sb.AppendLine($"{indent}public static class {className}");
            sb.AppendLine($"{indent}{{");
            foreach (var item in list)
            {
                sb.AppendLine($"{indent}    public static JsonConstNode {item} = new (\"{path}{seperator}{item}\");");
                endpaths.Add($"{path}.{item}");
            }
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            sb.AppendLine($"{indent}public static JsonConstNode {className} = new (\"{path}\");");
            endpaths.Add(path);
        }
    }
}
