using JsonConstGenerator;
using JsonConstGenerator.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using MiniJSON;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Threading;
using System.Xml.Linq;

[Generator]
internal class JsonConstIncrementalGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //if (!Debugger.IsAttached) Debugger.Launch();
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "JsonConstGenerator.JsonConstGeneratorAttribute",
                IsTargetClass,
                TransformAttributesToGeneratorInput)
            .SelectMany((inputs, _) => inputs);

        context.RegisterSourceOutput(provider, ProcessGeneratorInput);
    }

    // Determines if the node is a class we care about
    private static bool IsTargetClass(SyntaxNode node, CancellationToken ct)
    {
        return node is ClassDeclarationSyntax;
    }


    // Transform each attribute on a class into a GeneratorInput
    private static IEnumerable<GeneratorInput> TransformAttributesToGeneratorInput(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        // Extract class info
        var classSyntax = (ClassDeclarationSyntax)ctx.TargetNode;
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        // Loop over each attribute separately
        foreach (var attribute in ctx.Attributes)
        {
            yield return new GeneratorInput(classSyntax, classSymbol, attribute);
        }
    }

    // Process each valid GeneratorInput
    private static void ProcessGeneratorInput(SourceProductionContext spc, GeneratorInput input)
    {
        // Attach debugger if needed (optional)
        //if (!Debugger.IsAttached) Debugger.Launch();

        // Validate the class
        if (!Validation.TryValidateClass(spc, input.ClassSyntax, input.ClassSymbol, input.Attribute))
        {
            // Stop processing this attribute only
            return;
        }

        
        var modifiers = GeneratorHelper.GetClassModifiers(input.ClassSymbol);
        var namespaceName = GeneratorHelper.GetNamespace(input.ClassSymbol);
        var className = input.ClassSymbol.Name;
        var seperator = GeneratorHelper.GetOptionalPropertyFromAttribute(input.Attribute, "Separator", ".");
        var camelCase = GeneratorHelper.GetOptionalPropertyFromAttribute(input.Attribute, "UpperCamelCase", false);

        var fileDir = Path.GetDirectoryName(input.ClassSyntax.SyntaxTree.FilePath);

        var fileNames = input.Attribute.ConstructorArguments.Length > 0
            ? input.Attribute.ConstructorArguments[0].Values.Select(v => v.Value?.ToString() ?? "").ToArray()
            : Array.Empty<string>();


        var filePaths = GetJsonFilePaths(input, fileNames, spc, fileDir);

        var relativePaths = filePaths.Select(fp => fp.Substring(fileDir.Length+1)).ToArray();

        //if (!Debugger.IsAttached) Debugger.Launch();
        var dict = JsonMerger.MergeJsonFiles(filePaths, spc, input.Attribute);

        if(dict == null || !dict.Any())
            return;


        var sb = new StringBuilder();
        var sb2 = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"using JsonConstGenerator;");
        sb.AppendLine($"using JsonConstGenerator.{className};");
        sb.AppendLine($"namespace {namespaceName ?? "global"}");
        sb.AppendLine($"{{");

        // ⚡ Add comment about generated files
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Generated from {string.Join(", ", relativePaths)}");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    {modifiers} partial class {className}");
        sb.AppendLine($"    {{");


        sb2.AppendLine($"namespace JsonConstGenerator.{className}");
        sb2.AppendLine($"{{");


        // Generate content from the merged dictionary
        GenerateFromMergedJson(dict, sb, sb2, seperator, camelCase);

        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");
        sb2.AppendLine($"}}");

        // Append the generated classes at the end of the file
        spc.AddSource($"{className}_JsonConst.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        spc.AddSource($"{className}_Models.g.cs", SourceText.From(sb2.ToString(), Encoding.UTF8));
    }

    private static string[] GetJsonFilePaths(GeneratorInput input, string[] filePaths, SourceProductionContext spc, string projectDir)
    {
        var resolvedFiles = new List<string>();

        foreach (var path in filePaths)
        {
            //if (!Debugger.IsAttached) Debugger.Launch();

            // absolute path from project root
            var absolutePath = Path.Combine(projectDir, path);

            // wildcard support
            if (absolutePath.Contains("*") || absolutePath.Contains("?"))
            {
                var matches = ResolveWildcardPath(projectDir, path);
                if (matches.Length == 0)
                {
                    ReportMissingFile(path, projectDir);
                    continue;
                }
                resolvedFiles.AddRange(matches);
            }
            else if (File.Exists(absolutePath))
            {
                resolvedFiles.Add(absolutePath);
            }
            else
            {
                ReportMissingFile(path, projectDir);
            }
        }
        return resolvedFiles.Distinct().ToArray();

        void ReportMissingFile(string path, string dir)
        {
            var attrSyntax = input.Attribute.ApplicationSyntaxReference?.GetSyntax() as AttributeSyntax;
            Location location = attrSyntax?.GetLocation() ?? Location.None;
            var diag = Diagnostic.Create(
                Diagnostics.MissingJsonFileDescriptor,
                location,
                path,
                dir);
            spc.ReportDiagnostic(diag);
        }

        string[] ResolveWildcardPath(string baseDir, string relativePath)
        {
            //if (!Debugger.IsAttached) Debugger.Launch();
            // Normalize path separators
            relativePath = relativePath.Replace('/', Path.DirectorySeparatorChar).Replace('\\', Path.DirectorySeparatorChar);
            var segments = relativePath.Split(Path.DirectorySeparatorChar);

            // Start with the base directory
            var currentPaths = new List<string> { baseDir };

            for (int i = 0; i < segments.Length; i++)
            {
                var segment = segments[i];
                var isLastSegment = i == segments.Length - 1;
                var nextPaths = new List<string>();

                foreach (var currentPath in currentPaths)
                {
                    if (!Directory.Exists(currentPath))
                        continue;

                    if (segment.Contains("*"))
                    {
                        if (isLastSegment)
                        {
                            // File pattern
                            try
                            {
                                nextPaths.AddRange(Directory.GetFiles(currentPath, segment));
                            }
                            catch { /* ignore inaccessible directories */ }
                        }
                        else
                        {
                            // Directory pattern
                            try
                            {
                                nextPaths.AddRange(Directory.GetDirectories(currentPath, segment));
                            }
                            catch { /* ignore inaccessible directories */ }
                        }
                    }
                    else
                    {
                        // Exact match
                        var combined = Path.Combine(currentPath, segment);
                        if (isLastSegment)
                        {
                            if (File.Exists(combined))
                                nextPaths.Add(combined);
                        }
                        else
                        {
                            if (Directory.Exists(combined))
                                nextPaths.Add(combined);
                        }
                    }
                }

                currentPaths = nextPaths;
            }

            return currentPaths.ToArray();
        }

    }




    private static void GenerateFromMergedJson(
    Dictionary<string, object> dict,
    StringBuilder sb,
    StringBuilder sb2,
    string separator,
    bool camelCase)
    {
        if (dict == null || !dict.Any())
            return;

        if(camelCase)
        {
            dict = dict.ToDictionary(kvp => char.ToUpper(kvp.Key[0]) + kvp.Key.Substring(1), kvp => kvp.Value);
        }

        var allNodes = new List<string>();      // All top-level node names
        var endNodes = new List<string>();      // Nodes without children
        var parentNodes = new List<string>();   // Nodes with children
        var generatedClasses = new HashSet<string>(); // Track generated class types

        // Generate each top-level property
        foreach (var item in dict)
        {
            allNodes.Add(item.Key);
            GenerateNodeDeclaration(item.Key, item.Value, sb, sb2, 2, item.Key, separator, camelCase, endNodes, parentNodes, generatedClasses);
        }

        sb.AppendLine();

        // Generate GetAllNodes()
        GenerateGetAllNodesMethod(sb, parentNodes);

        // Generate GetAllEndNodes()
        GenerateGetAllEndNodesMethod(sb, parentNodes);

        // Generate FindNode()
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Finds a single node by its path.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IConstNode FindNode(string path) => GetAllNodes().First(x => x.NodePath == path);");
        sb.AppendLine();

        // Generate TryFindNode()
        sb.AppendLine("        public static bool TryFindNode(string path, out IConstNode node)");
        sb.AppendLine("        {");
        sb.AppendLine("            node = GetAllNodes().FirstOrDefault(x => x.NodePath == path);");
        sb.AppendLine("            return node != null;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate GetNodeValue<T>()
        sb.AppendLine("        public static T GetNodeValue<T>(string path)");
        sb.AppendLine("        {");
        sb.AppendLine("            var node = FindNode(path);");
        sb.AppendLine("            if (node is IValueConstNode valueNode)");
        sb.AppendLine("                return (T)valueNode.NodeValue;");
        sb.AppendLine("            throw new InvalidOperationException($\"Node '{path}' is not a value node.\");");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Generate _allNodes array
        sb.AppendLine("        private static readonly IConstNode[] _allNodes =");
        sb.AppendLine("        {");
        foreach (var node in allNodes)
        {
            sb.AppendLine($"            {node},");
        }
        sb.AppendLine("        };");
        sb.AppendLine();

        // Generate _allEndNodes array
        sb.AppendLine("        private static readonly IConstNode[] _allEndNodes =");
        sb.AppendLine("        {");
        foreach (var node in endNodes)
        {
            sb.AppendLine($"            {node},");
        }
        sb.AppendLine("        };");
    }

    private static void GenerateNodeDeclaration(
        string name,
        object value,
        StringBuilder sb,
        StringBuilder sb2,
        int indentLevel,
        string path,
        string separator,
        bool camelCase,
        List<string> endNodes,
        List<string> parentNodes,
        HashSet<string> generatedClasses)
    {
        string indent = new string(' ', indentLevel * 4);

        if (value is Dictionary<string, object> dict && dict.Any())
        {
            if (camelCase)
            {
                dict = dict.ToDictionary(kvp => char.ToUpper(kvp.Key[0]) + kvp.Key.Substring(1), kvp => kvp.Value);
            }
            // Parent node with children - use object initializer
            parentNodes.Add(name);
            string className = path.Replace(separator, string.Empty);

            sb.AppendLine($"{indent}public static readonly {className} {name} = new()");
            sb.AppendLine($"{indent}{{");

            var childEndNodes = new List<string>();
            var childParentNodes = new List<string>();

            foreach (var item in dict)
            {
                GenerateChildInitializer(item.Key, item.Value, sb, sb2, indentLevel + 1, $"{path}{separator}{item.Key}", separator, camelCase, childEndNodes, childParentNodes, generatedClasses);
            }

            sb.AppendLine($"{indent}}};");
            sb.AppendLine();

            // Generate the class in sb2
            if (generatedClasses.Add(className))
            {
                GenerateNodeClass(className, dict, sb2, path, separator, childEndNodes, childParentNodes, generatedClasses);
            }
        }
        else if (value is List<object> list && list.Any() && list.All(x => x is string))
        {
            // String array - generates child nodes for each item
            parentNodes.Add(name);
            string className = path.Replace(separator, string.Empty);

            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Path: <c>{path}</c>");
            sb.AppendLine($"{indent}/// Type: <c>string[]</c> {EscapeXmlValue(" -> ")} [<c>{EscapeXmlValue(string.Join(", ", list.Select(x => $"\"{x}\"")))}]</c>");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public static readonly {className} {name} = new()");
            sb.AppendLine($"{indent}{{");

            foreach (var item in list)
            {
                string itemName = item?.ToString() ?? "";
                sb.AppendLine($"{indent}    {itemName} = new(\"{path}{separator}{itemName}\"),");
            }

            sb.AppendLine($"{indent}}};");
            sb.AppendLine();

            // Generate the class in sb2
            if (generatedClasses.Add(className))
            {
                GenerateStringArrayClass(className, list.Cast<string>().ToList(), sb2, path, separator);
            }
        }
        else if (value == null || (value is List<object> emptyList && !emptyList.Any()) || (value is Dictionary<string, object> emptyDict && !emptyDict.Any()))
        {
            // Null, empty array, or empty object - ValueLessConstNode
            endNodes.Add(name);
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Path: <c>{path}</c>");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"{indent}public static readonly ValueLessConstNode {name} = new(\"{path}\");");
            sb.AppendLine();
        }
        else
        {
            var (typeName, valueString) = GetValueTypeAndLiteral(value);
            

            // Primitive value
            endNodes.Add(name);
            GeneratePropertySummary(sb, value, path);
            if (typeName == "object")
            {
                sb.AppendLine($"{indent}public static readonly ValueLessConstNode {name} = new(\"{path}\");");
            }
            else
            {
                sb.AppendLine($"{indent}public static readonly ValueConstNode<{typeName}> {name} = new(\"{path}\", {valueString});");
            }
            
            sb.AppendLine();
        }
    }

    private static void GenerateChildInitializer(
        string name,
        object value,
        StringBuilder sb,
        StringBuilder sb2,
        int indentLevel,
        string path,
        string separator,
        bool camelCase,
        List<string> endNodes,
        List<string> parentNodes,
        HashSet<string> generatedClasses)
    {
        string indent = new string(' ', indentLevel * 4);

        if (value is Dictionary<string, object> dict && dict.Any())
        {
            if (camelCase)
            {
                dict = dict.ToDictionary(kvp => char.ToUpper(kvp.Key[0]) + kvp.Key.Substring(1), kvp => kvp.Value);
            }
            parentNodes.Add(name);
            string className = $"{name}ConstNode";

            sb.AppendLine($"{indent}{name} = new()");
            sb.AppendLine($"{indent}{{");

            var childEndNodes = new List<string>();
            var childParentNodes = new List<string>();

            foreach (var item in dict)
            {
                GenerateChildInitializer(item.Key, item.Value, sb, sb2, indentLevel + 1, $"{path}{separator}{item.Key}", separator, camelCase, childEndNodes, childParentNodes, generatedClasses);
            }

            sb.AppendLine($"{indent}}},");

            if (generatedClasses.Add(className))
            {
                GenerateNodeClass(className, dict, sb2, path, separator, childEndNodes, childParentNodes, generatedClasses);
            }
        }
        else if (value is List<object> list && list.Any() && list.All(x => x is string))
        {
            parentNodes.Add(name);
            string className = $"{name}ConstNode";

            sb.AppendLine($"{indent}{name} = new()");
            sb.AppendLine($"{indent}{{");

            foreach (var item in list)
            {
                string itemName = item?.ToString() ?? "";
                sb.AppendLine($"{indent}    {itemName} = new(\"{path}{separator}{itemName}\"),");
            }

            sb.AppendLine($"{indent}}},");

            if (generatedClasses.Add(className))
            {
                GenerateStringArrayClass(className, list.Cast<string>().ToList(), sb2, path, separator);
            }
        }
        else if (value == null || (value is List<object> emptyList && !emptyList.Any()) || (value is Dictionary<string, object> emptyDict && !emptyDict.Any()))
        {
            endNodes.Add(name);
            sb.AppendLine($"{indent}{name} = new(\"{path}\"),");
        }
        else
        {
            endNodes.Add(name);

            if (path == name) // Top-level node, include type and value in summary, child nodes have their summaries in their subclasses
                GeneratePropertySummary(sb, value, path);

            var (valueType, valueString) = GetValueTypeAndLiteral(value);

            if (valueType == "object")
                sb.AppendLine($"{indent}{name} = new(\"{path}\"),");
            else
                sb.AppendLine($"{indent}{name} = new(\"{path}\", {valueString}),");
        }
    }

    private static (string typeName, string literal) GetValueTypeAndLiteral(object value)
    {
        return value switch
        {
            bool b => ("bool", b ? "true" : "false"),
            int i => ("int", i.ToString()),
            long l => HandleLong(l),
            double d => ("double", FormatDoubleLiteral(d)),
            string s => ("string", $"\"{s.Replace("\"", "\\\"")}\""),
            _ => ("object", value?.ToString() ?? "null")
        };
    }
    private static (string typeName, string literal) HandleLong(long l)
    {
        if (l < int.MaxValue && l > int.MinValue)
            return ("int", l.ToString());

        return ("long", $"{l}");
    }

    private static string FormatDoubleLiteral(double value)
    {
        var str = value.ToString("G", System.Globalization.CultureInfo.InvariantCulture);
        // Ensure the literal has a decimal point so it's recognized as a double
        if (!str.Contains(".") && !str.Contains("E"))
            str += ".0";
        return str;
    }

    private static void GenerateGetAllNodesMethod(StringBuilder sb, List<string> parentNodes)
    {
        sb.AppendLine("        public static IEnumerable<IConstNode> GetAllNodes()");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var node in _allNodes)");
        sb.AppendLine("                yield return node;");
        sb.AppendLine();
        foreach (var parent in parentNodes)
        {
            sb.AppendLine($"            foreach (var child in {parent}.GetChildNodesRecursive())");
            sb.AppendLine("                yield return child;");
            sb.AppendLine();
        }
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateGetAllEndNodesMethod(StringBuilder sb, List<string> parentNodes)
    {
        sb.AppendLine("        public static IEnumerable<IConstNode> GetAllEndNodes()");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var node in _allEndNodes)");
        sb.AppendLine("                yield return node;");
        sb.AppendLine();
        foreach (var parent in parentNodes)
        {
            sb.AppendLine($"            foreach (var child in {parent}.GetChildEndNodesRecursive())");
            sb.AppendLine("                yield return child;");
            sb.AppendLine();
        }
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateNodeClass(
        string className,
        Dictionary<string, object> dict,
        StringBuilder sb2,
        string path,
        string separator,
        List<string> childEndNodes,
        List<string> childParentNodes,
        HashSet<string> generatedClasses)
    {
        sb2.AppendLine($"    public class {className} : IParentConstNode");
        sb2.AppendLine("    {");
        sb2.AppendLine($"        public string NodePath => \"{path}\";");
        sb2.AppendLine();

        // Generate properties for each child
        foreach (var item in dict)
        {
            var propType = GetPropertyType(item.Key, item.Value);

            // Generate XML summary
            GeneratePropertySummary(sb2, item.Value, $"{path}{separator}{item.Key}");
            sb2.AppendLine($"        public {propType} {item.Key} {{ get; init; }}");
            sb2.AppendLine();
        }

        sb2.AppendLine();
        GenerateClassHelperMethods(sb2, childEndNodes, childParentNodes);
        sb2.AppendLine("    }");
        sb2.AppendLine();
    }

    private static void GenerateStringArrayClass(string className, List<string> items, StringBuilder sb2, string path, string separator)
    {
        sb2.AppendLine($"    public class {className} : IParentConstNode, IValueConstNode<string[]>");
        sb2.AppendLine("    {");
        sb2.AppendLine($"        public string NodePath => \"{path}\";");
        sb2.AppendLine($"        public string[] NodeValue => new[] {{ {string.Join(", ", items.Select(i => $"\"{i}\""))} }};");
        sb2.AppendLine("        object IValueConstNode.NodeValue => NodeValue;");
        sb2.AppendLine();

        foreach (var item in items)
        {
            var itemPath = $"{path}{separator}{item}";
            sb2.AppendLine($"        /// <summary>");
            sb2.AppendLine($"        /// Path: <c>{itemPath}</c>");
            sb2.AppendLine($"        /// </summary>");
            sb2.AppendLine($"        public ValueLessConstNode {item} {{ get; init; }}");
        }

        sb2.AppendLine();
        sb2.AppendLine("        public IEnumerable<IConstNode> GetChildEndNodesRecursive()");
        sb2.AppendLine("        {");
        foreach (var item in items)
        {
            sb2.AppendLine($"            yield return {item};");
        }
        sb2.AppendLine("        }");
        sb2.AppendLine();
        sb2.AppendLine("        public IEnumerable<IConstNode> GetChildNodesRecursive() => GetChildEndNodesRecursive();");
        sb2.AppendLine("        public IEnumerable<IConstNode> GetChildNodes() => GetChildEndNodesRecursive();");
        sb2.AppendLine("        public override string ToString() => NodePath;");
        sb2.AppendLine($"        public static implicit operator string[] ({className} node) => node.NodeValue;");
        sb2.AppendLine("    }");
        sb2.AppendLine();
    }

    private static string GetPropertyType(string name, object value)
    {
        if (value is Dictionary<string, object> dict && dict.Any())
            return $"{name}ConstNode";
        if (value is List<object> list && list.Any() && list.All(x => x is string))
            return $"{name}ConstNode";
        if (value == null || (value is List<object> emptyList && !emptyList.Any()) || (value is Dictionary<string, object> emptyDict && !emptyDict.Any()))
            return "ValueLessConstNode";

        var (valueType, _) = GetValueTypeAndLiteral(value);
        return valueType switch
        {
            "bool" => "ValueConstNode<bool>",
            "int" => "ValueConstNode<int>",
            "long" => "ValueConstNode<long>",
            "double" => "ValueConstNode<double>",
            "string" => "ValueConstNode<string>",
            _ => "ValueLessConstNode"
        };
    }

    private static void GenerateClassHelperMethods(StringBuilder sb2, List<string> endNodes, List<string> parentNodes)
    {
        // GetChildNodes
        sb2.AppendLine("        public IEnumerable<IConstNode> GetChildNodes()");
        sb2.AppendLine("        {");
        foreach (var node in endNodes.Concat(parentNodes))
        {
            sb2.AppendLine($"            yield return {node};");
        }
        sb2.AppendLine("        }");
        sb2.AppendLine();

        // GetChildNodesRecursive
        sb2.AppendLine("        public IEnumerable<IConstNode> GetChildNodesRecursive()");
        sb2.AppendLine("        {");
        sb2.AppendLine("            foreach (var child in GetChildNodes())");
        sb2.AppendLine("            {");
        sb2.AppendLine("                yield return child;");
        sb2.AppendLine("                if (child is IParentConstNode parent)");
        sb2.AppendLine("                    foreach (var sub in parent.GetChildNodesRecursive())");
        sb2.AppendLine("                        yield return sub;");
        sb2.AppendLine("            }");
        sb2.AppendLine("        }");
        sb2.AppendLine();

        // GetAllNodes / GetAllEndNodes
        sb2.AppendLine("        public IEnumerable<IConstNode> GetAllNodes() => GetChildNodesRecursive();");
        sb2.AppendLine("        public IEnumerable<IConstNode> GetAllEndNodes()");
        sb2.AppendLine("        {");
        sb2.AppendLine("            foreach (var child in GetChildNodesRecursive())");
        sb2.AppendLine("                if (child is not IParentConstNode)");
        sb2.AppendLine("                    yield return child;");
        sb2.AppendLine("        }");
        sb2.AppendLine();

        // GetChildEndNodesRecursive
        sb2.AppendLine("        public IEnumerable<IConstNode> GetChildEndNodesRecursive()");
        sb2.AppendLine("        {");
        sb2.AppendLine("            foreach (var child in GetChildNodes())");
        sb2.AppendLine("            {");
        sb2.AppendLine("                if (child is IParentConstNode parent)");
        sb2.AppendLine("                {");
        sb2.AppendLine("                    foreach (var endNode in parent.GetChildEndNodesRecursive())");
        sb2.AppendLine("                        yield return endNode;");
        sb2.AppendLine("                }");
        sb2.AppendLine("                else");
        sb2.AppendLine("                {");
        sb2.AppendLine("                    yield return child;");
        sb2.AppendLine("                }");
        sb2.AppendLine("            }");
        sb2.AppendLine("        }");
        sb2.AppendLine();

        sb2.AppendLine("        public override string ToString() => NodePath;");
    }

    private static void GeneratePropertySummary(StringBuilder sb2, object value, string path)
    {
        sb2.AppendLine($"        /// <summary>");
        sb2.AppendLine($"        /// Path: <c>{path}</c>");

        // Only add value info for primitive values (not for nested objects/arrays)
        if (value != null &&
            !(value is Dictionary<string, object>) &&
            !(value is List<object>))
        {
            var (typeName, literalValue) = GetValueTypeAndLiteral(value);
            if(typeName == "object")
                sb2.AppendLine($"        /// <para>Type: <c>unsupported object</c>");
            else
                sb2.AppendLine($"        /// <para>Type: <c>{typeName}</c>  {EscapeXmlValue("->")}  <c>{EscapeXmlValue(literalValue)}</c></para>");
        }

        sb2.AppendLine($"        /// </summary>");
    }

    private static string EscapeXmlValue(string value)
    {
        return value
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;");
    }
}
